# A sample Gemfile
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'

group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
